name: Publish Test Report

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Configura el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configura .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      # 3. Instala dependencias
      - name: Restore dependencies
        run: dotnet restore

      # 4. Ejecuta las pruebas
      - name: Run tests and generate report
        run: |
          dotnet test --collect:"XPlat Code Coverage"
          # Genera el reporte HTML
          mkdir -p output
          mv TestReport.html output/

      # 5. Despliega el reporte en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
